### ISSUE TITLE
Electricity investment costs and stranded asset calculation by Plutus 

### ISSUE THREAD

**Issue by Shukla02Nikita** [JGCRI/plutus#24]
@mengqi-z
Hi, Zhao, I am Nikita Shukla, an energy modeling professional based in New Delhi, India. I am interested in understanding the specific methodology employed to calculate electricity investment costs and stranded asset valuation in Plutus. In other words, the background calculations.

**Comment by mengqi-z** [comment]
@Shukla02Nikita
In addition to the information Page provided in this [issue](https://github.com/JGCRI/gcam-core/issues/350), [Binsted et al., 2020](https://iopscience.iop.org/article/10.1088/1748-9326/ab506d) also documented the methodology of calculating stranded assets. `plutus`'s methodology is based on his paper.

**Comment by Shukla02Nikita** [comment]
I appreciate your response. While I have comprehended the methodology for stranded assets, I would greatly appreciate your assistance in elucidating the approach for calculating "electricity investment costs" in scenarios where I intend to perform these calculations outside of the GCAM model, specifically within the framework of Excel.
